SELECT * FROM customer_behaviour.customer;

#1) What is the total revenue generated by male vs female customers?  
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;
#RESULT: Men spend more than women, generating more revenue for the company. 

#2) Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
#a subquery is a query within another query, aggregates are computed in the select statement and if they're not we use subquery as an advantage
#plus you cant use aggregates in where statements 


#3) Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_rating
FROM customer 
GROUP BY item_purchased
ORDER BY avg_rating desc
LIMIT 5;
#RESULT: We can see the top reviewed products and highlight them for marketing programs or sell these products at a premium price 

#4) Compare the average purchase amounts between standard and express shipping?
SELECT shipping_type, AVG(purchase_amount)
FROM customer 
WHERE shipping_type IN('Express', 'Standard')
GROUP BY shipping_type;
#RESULT: Company should focus more on faster shipping options for customers

#5) Do subscribed customers spend more? Compare average spend and total revenue between subscribed and un-subscribed costumers 
SELECT subscription_status, COUNT(customer_id), ROUND(AVG(purchase_amount),2) AS avg_spent, ROUND(SUM(purchase_amount),2) AS total_spent
FROM customer
GROUP BY subscription_status;

#6) Which 5 products have the highest percentage of purchases with discounts applied? (COUNTING HOW MANY DISCOUNTS OCCURED)
SELECT item_purchased, 
CONCAT(ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2), '%') AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
#RESULT: products the rely heavily on coupons/discounts 
#discount rate = number of purchases of that product with a discount / total number of purchases of that product x 100

#7) Segment customers into new, returning, loyal based on total number of purchases and 
#show the count of each segment (basically customer segmentation)
SELECT COUNT(customer_id), 
CASE 
	WHEN previous_purchases <2 THEN 'New'
	WHEN previous_purchases >=2 AND previous_purchases <=10 THEN 'Returning'
    WHEN previous_purchases >10 THEN 'Loyal'
    END AS customer_behaviour
FROM customer
GROUP BY customer_behaviour;

#8) What are the 3 most purchased products WITHIN each category?
#you can not aggregate inside a count function

#We will use CTE, windows and 
WITH total_breakdown AS (SELECT category, item_purchased, 
COUNT(item_purchased) AS total_orders, ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer 
GROUP BY category, item_purchased)

SELECT category, item_purchased, item_rank, total_orders
FROM total_breakdown
WHERE item_rank <=3; 
#used row number instead of dense ranks as dense rank will put the values with the same amount purchased into the same number rank

#9) Are customers that are repeat buyers with more than 5 previous purchases more likely to subscribe?
SELECT COUNT(customer_id), subscription_status
FROM customer
GROUP BY subscription_status;

#Repeat buyers tend to become subscribed customers

#10) What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group; 






